# Generated by Django 5.1.5 on 2025-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
